# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

sphinx:
  configuration: docs/conf.py

python:
   setup_py_install: true