"""
Main program invoked by the turboSETI bash script
generated by setup.py during installation.
"""

import sys
import logbook
from ..log import logger_group
import time
from argparse import ArgumentParser
from .find_doppler import FindDoppler


def main(args=None):
    """This is the entry-point to turboSETI.

    Args:
      args: (Default value = None)

    Returns:

    """
    # Create an option parser to get command-line input/arguments
    p = ArgumentParser(description='turboSETI doppler drift narrowband search utility.')

    p.add_argument('filename', type=str, help='Name of filename to open (h5 or fil)')
    p.add_argument('-M', '--max_drift', dest='max_drift', type=float, default=10.0,
                   help='Set the drift rate to search. Unit: Hz/sec. Default: 10.0')
    p.add_argument('-s', '--snr', dest='snr', type=float, default=25.0,
                   help='SNR threshold. Default: 25.0')
    p.add_argument('-o', '--out_dir', dest='out_dir', type=str, default='./',
                   help='Location for output files. Default: local dir. ')
    p.add_argument('-l', '--loglevel', dest='loglevel', type=str, default='warn',
                   help='Specify log level (warn, info, debug)')
    p.add_argument('-c', '--coarse_chans', dest='coarse_chans', type=str, default=None,
                   help='Comma separated list of coarse channels to analyze.')
    p.add_argument('-n', '--n_coarse_chan', dest='n_coarse_chan', type=int, default=None,
                   help='Number of coarse channels in file.')
    p.add_argument('-p', '--n_parallel', dest='n_parallel', type=int, default=1,
                   help='Number of partitions to run in parallel. Default to 1 (single partition)')
    p.add_argument('-b', '--progress_bar', dest='flag_progress_bar', type=str, default='y',
                   help='Use a progress bar? (y/n)')
    p.add_argument('-f', '--fscrunch', dest='fscrunch', type=int, default=1,
                   help='Number of channels to scrunch to (should be power 2).')

    if args is None:
        args = p.parse_args()
    else:
        args = p.parse_args(args)

    if args.coarse_chans is None:
        coarse_chans = ''
    else:
        coarse_chans = map(int, args.coarse_chans.split(','))

    # Setting log level
    if args.loglevel == 'warn':
        logger_group.level = logbook.WARNING
    elif args.loglevel == 'info':
        logger_group.level = logbook.INFO
    elif args.loglevel == 'debug':
        logger_group.level = logbook.DEBUG
    else:
        raise ValueError('Need valid loglevel value (warn, info, debug).')

    #Doing search
    try:
        t0 = time.time()


        find_seti_event = FindDoppler(args.filename, max_drift=args.max_drift,
                                      snr=args.snr, out_dir=args.out_dir,
                                      coarse_chans=coarse_chans, obs_info=None,
                                      n_coarse_chan=args.n_coarse_chan, fscrunch=args.fscrunch)

        find_seti_event.search(n_partitions=args.n_parallel,
                               progress_bar=args.flag_progress_bar)

        t1 = time.time()
        print('Search time: %5.2f min' % ((t1-t0)/60.))

    except Exception as e:
        raise Exception(1, '[turbo_SETI] Some issue with FindDoppler.', e)

if __name__ == '__main__':
    main()
